# Basic distro definition to include graphic requirements and systemd
# Assign in local.conf of build directory
require conf/distro/poky.conf
DISTRO = "plgraphic"

# Change hostname to plfluidic instead of raspberrypi4-64
hostname:pn-base-files = "plfluidic"

# System capabilities
DISTRO_FEATURES:append = " wayland opengl pam systemd"
INIT_MANAGER = "systemd"

PREFERRED_PROVIDER_virtual/wpebackend = "wpebackend-fdo"

# Desktop interface
WESTON_USER = "root"

# Set root password to plfluidic and create 'user' account with same password
INHERIT += "extrausers"
EXTRA_USERS_PARAMS = "usermod -p \$(openssl passwd -6 'plfluidic') root; \
    useradd -p \$(openssl passwd -6 'plfluidic') user; \
    usermod -a -G sudo user; \
"

# Policy required for RPi4 features
LICENSE_FLAGS_ACCEPTED = "synaptics-killswitch"
